[package]
name = "mdf2016"
version = "0.1.0"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
petgraph = "0.7.1"
rand = { version = "0.9.0", features = ["std_rng"] }
